---
include:
  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
    artifact-name: corne_left
  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view
    artifact-name: corne_right
  # - board: nice_nano_v2
  #   shield: corne_left nice_view_adapter nice_view settings_reset
  #   snippet: studio-rpc-usb-uart
  #   artifact-name: reset_corne_left
  # - board: nice_nano_v2
  #   shield: corne_right nice_view_adapter nice_view settings_reset
  #   snippet: studio-rpc-usb-uart
  #   artifact-name: reset_corne_right
  # - board: nice_nano_v2
  #   shield: corne_left nice_view_adapter nice_view
  #   snippet: studio-rpc-usb-uart zmk-usb-logging
  #   artifact-name: usblogging_corne_left
  # - board: nice_nano_v2
  #   shield: corne_right nice_view_adapter nice_view
  #   snippet: studio-rpc-usb-uart zmk-usb-logging
  #   artifact-name: usblogging_corne_right